apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-httpd-service
spec:
  selector:
    app: httpd
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: {{ .Values.httpd.service.type }}

