apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: http-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: httpd-deployment
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60 
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 10  # 안정화 대기 시간
      policies:
      - type: Pods
        value: 1  # CPU 사용량이 기준 이하일 때 Pod 수를 1개씩 줄임
        periodSeconds: 20  # 이 정책의 유효 기간
